# Site settings
title: Dudu‘s Blog
SEOTitle: 都都的博客 | Dudu's Blog
header-img: img/home-bg.jpg
email: Qijia2011@gmail.com
description: "都都的日常关于生活、学习、编程、电影的博客 | 都都，Web & Mobile Lover，Movies，Scratch Designer "
keyword: "都都, 都都欢乐玩具屋, Dudu, dudu, @qijia2011, 都都的博客,"
url: "https://qijia2011.github.io/"              # your host, for absolute URL
baseurl: ""                             # for example, '/blog' if your blog hosted on 'host/blog'

# Publish posts or collection documents with a future date.
future: true

# SNS settings
RSS: false
weibo_username:     qijiazhuo
github_username:    qijia2011



# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","README.zh.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`
# If you have timezone issue (e.g. #68) in China, uncomment to use this:
timezone: CN  



# Gems
# from PR#40, to support local preview for Jekyll 3.0
# make sure you have this gem installed
# `$ gem install jekyll-paginate`
#plugins: [jekyll-paginate]

gems: [jekyll-paginate]

# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1



# Disqus settings
#disqus_username: qijia2011

# Netease settings
netease_comment: false



# Analytics settings
# Baidu Analytics 
# ba_track_id: [your track id]


# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "Happy to be continued...<br>快乐继续每一天"
sidebar-avatar: /img/HappyFamily.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value



# Progressive Web Apps
chrome-tab-theme-color: "#db5945"
service-worker: true



# MathJax rendering for layout:page (e.g. post preview)
page-mathjax: false



# Friends
friends: [
    {
            title: "云中客",
        href: "http://zkgh2011.com/"
    },{
        title: "云飞飞",
        href: "http://zkgh2011.com/"
    }
]
